<?php


class DynamicImageTest extends \Codeception\Test\Unit
{
    /**
     * @var \UnitTester
     */
    protected $tester;

    private $testData = [
        'width' => 500,
        'height' => 500,
        'filename' => 'deadpool.jpg',
        'exceptions' => true,
        'debug' => false,
        'invalidate_cache' => 0
    ];

    protected function _before()
    {
        require_once __DIR__ . '/../../DynamicImage.php';
    }

    protected function _after()
    {
    }

    /**
     *  @group main
     */
    public function testFull()
    {
        $this->deleteImage(__DIR__ . '/../../deadpool-500x500.jpg');

        $di = new DynamicImage($this->testData);
    }

    /**
     *  @group main
     */
    public function testMissingParams()
    {
        // Make sure by the end of the test error has been set to true
        $error = false;

        try {
            // Unset the height parameter that is required
            $data = $this->testData; 
            unset($data['height']);
            $di = new DynamicImage($data);
        } catch(Exception $e) {
            $error = true;
            $this->assertEquals('You are missing one of the required parameters.', $e->getMessage());
        }

        $this->assertTrue($error);
    }

    /**
     *  @group main
     */
    public function testImageMissing()
    {
        // Make sure by the end of the test error has been set to true
        $error = false;

        try {
            $data = $this->testData;
            $data['filename'] = 'missing.jpg';
            $this->deleteImage(__DIR__ . '/../../cache/missing-500x500.jpg');
            $di = new DynamicImage($data);
        } catch(Exception $e) {
            $error = true;
            $this->assertEquals('The image that you requested to generate could not be found.', $e->getMessage());
        }

        $this->assertTrue($error);
    }

    /**
     *  @group main
     */
    public function testMissingImageReturn()
    {
        $data = $this->testData;
        $data['image_missing'] = 'triangle.jpg';
        $data['filename'] = 'missing.jpg';
        $this->deleteImage(__DIR__ . '/../../cache/triangle-500x500.jpg');
        $di = new DynamicImage($data);
        $this->assertEquals('cache/triangle-500x500.jpg', $di->file);
    }

    /**
     *  @group main
     */
    public function testUnsupportedExtension()
    {
        // Make sure by the end of the test error has been set to true
        $error = false;

        $data = $this->testData;
        $data['filename'] = 'surf.gif';

        try {
            $di = new DynamicImage($data);
        } catch(Exception $e) {
            $error = true;
            $this->assertEquals('The filetype that you gave isn\'t supported.', $e->getMessage());
        }

        $this->assertTrue($error);
    }

    /**
     *  @group main
     */
    public function testImagePermissions()
    {
        // Make sure by the end of the test error has been set to true
        $error = false;

        $data = $this->testData;

        // Create test image file
        $fp = fopen(__DIR__ . '/../../test.jpg', 'w');

        // Set incorrect permissions for test file
        chmod(__DIR__ . '/../../test.jpg', 600);

        $data['filename'] = 'test.jpg';

        try {
            $di = new DynamicImage($data);
        } catch (Exception $e) {
            $error = true;
            $this->assertEquals('The original image doesn\'t have the correct permissions and cannot be generated.', $e->getMessage());
        }

        $this->assertTrue($error);

        unlink(__DIR__ . '/../../test.jpg');
    }

    /**
     *  @group cache
     */
    public function testCreatingCache()
    {
        // Make sure by the end of the test error has been set to true
        $error = false;

        // Directory of the cache
        $cacheDir = __dir__ . '/../../cache';

        // If the cache directory exists then delete it
        if (is_dir($cacheDir)) {
            // Delete all image file that are in the cache directory
            foreach (glob($cacheDir . "/*") as $file) {
                if (is_file($file)) {
                    unlink($file);
                }
            }

            // Delete the cache folder
            rmdir($cacheDir);
        }
        
        $data = $this->testData;

        try {
            // Delete image from cache that may be generated by test
            $this->deleteImage(__DIR__ . '/../../cache/deadpool-500x500.jpg');

            $di = new DynamicImage($data);
        } catch (Exception $e) {
            $error = true;
            $this->assertEquals('There was a problem when creating the `cache` directory. Please create it manually.', $e->getMessage());
        }

        $this->assertTrue($error);

        shell_exec("mkdir cache");
    }

    /**
     * @group loadTime
     */
    public function testGenerationTimes()
    {
        $output = new \Codeception\Lib\Console\Output([]);

        $data = $this->testData;

        $data['width'] = 500;
        $data['height'] = 500;

        $this->deleteImage(__DIR__ . '/../../cache/deadpool-500x500.jpg');

        $output->writeln("");
        $output->writeln(" Generating 500x500 image.");

        $start = microtime(true);
        $di = new DynamicImage($data);
        $end = microtime(true);

        // Check that function ran in less than 200 milliseconds
        $this->assertTrue(($start + ($end - $start)) < ($start + 0.2));

        $this->deleteImage(__DIR__ . '/../../cache/deadpool-5000x5000.jpg');

        $data['width'] = 5000;
        $data['height'] = 5000;

        $output->writeln(" Generating 5000x5000 image.");

        $start = microtime(true);
        $di = new DynamicImage($data);
        $end = microtime(true);

        // Check that the function ran in less than 2.5 seconds
        $this->assertTrue(($start + ($end - $start)) < ($start + 2.5));

        $this->deleteImage(__DIR__ . '/../../cache/deadpool-10000x10000.jpg');

        $data['width'] = 10000;
        $data['height'] = 10000;

        $output->writeln(" Generating 10000x10000 image.");

        $start = microtime(true);
        $di = new DynamicImage($data);
        $end = microtime(true);

        // Check that the function ran in less than 7.5 seconds
        $this->assertTrue(($start + ($end - $start)) < ($start + 7.5));
    }

    private function deleteImage($image)
    {
        if (file_exists($image)) {
            unlink($image);
        }
    }
}
